# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.222

# e.g. "flower"
species.name <- "hibiscus rosa"

# e.g. "red"
color <- "#FFFFFF"

# For list of colours available in R, see
# https://github.com/RSE-Sheffield/collaborative_github_exercise/tree/master/assets/Rcolor.pdf
