# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.962871
    
# e.g. "anas_krystallinus"    
species.name <- "birdy bird"
    
# e.g. "red"    
color <- "#CD1076"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
