# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.5
    
# e.g. "anas_krystallinus"    
species.name <- "Amy"
    
# e.g. "red"    
color <- "palevioletred1"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
