# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
set.seed(879546)
sig2 <- runif(1, min=0, max=5)

# e.g. "anas_krystallinus"
species.name <- "Carrot catticus"

# e.g. "red"
color <- "chartreuse3"

# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
