# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.1415926535
    
# e.g. "anas_krystallinus"    
species.name <- "Corvid_19"
    
# e.g. "red"    
color <- "midnightblue"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker