# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.8
    
# e.g. "anas_krystallinus"    
species.name <- "jamus_moorus"
    
# e.g. "red"    
color <- "black"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
