# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.4
    
# e.g. "anas_krystallinus"    
species.name <- "jean_du"
    
# e.g. "red"    
color <- "#CC79A7"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
