# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4 
    
# e.g. "anas_krystallinus"    
species.name <- julius_kantonus
    
# e.g. "red"    
color <-c("#EE1289") 
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker