# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.1
    
# e.g. "anas_krystallinus"    
species.name <- "Lesser-Spotted JMitchell98"
    
# e.g. "red"    
color <- "wheat"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
