# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.61
    
# e.g. "anas_krystallinus"    
species.name <- "Michael's bird"
    
# e.g. "red"    
color <- "darkorchid"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
