# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.2711
    
# e.g. "anas_krystallinus"    
species.name <- "Petroica macrocephala"
    
# e.g. "red"    
color <- "GREY7"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
