# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.51
    
# e.g. "anas_krystallinus"    
species.name <- "Alekhya's hawk"
    
# e.g. "red"    
color <- " azure4 "
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
