# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 3.00

# e.g. "anas_krystallinus"
species.name <- "marina_krystallinus "

# e.g. "red"
color <- "blue"

# For list of colours available in R, see
# https://github.com/RSE-Sheffield/collaborative_github_exercise/tree/master/assets/Rcolor.pdf
