# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.2
    
# e.g. "anas_krystallinus"    
species.name <- "bald_bearded_parakeet"
    
# e.g. "red"    
color <- "darkorange"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf