# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2
    
# e.g. "anas_krystallinus"    
species.name <- "sammus_harisonus"
    
# e.g. "red"    
color <- "#6e241a"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
