# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.5
    
# e.g. "anas_krystallinus"    
species.name <- "Sylvanus_benaksagensis"
    
# e.g. "red"    
color <- "red"

