# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 1.25
    
# e.g. "anas_krystallinus"    
species.name <- "thomas_greenus"
    
# e.g. "red"    
color <- "chartreuse"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
