# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 0.1

# e.g. "anas_krystallinus"
species.name <- "tortola"
    
# e.g. "red"
color <- "green"

# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
