# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2.9
    
# e.g. "anas_krystallinus"    
species.name <- "windo_hutabaratus"
    
# e.g. "red"    
color <- "#fc03ba"
    
# tip: pick a color at using rstudio colour picker. Addins > Colour Picker
